<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BureauEtudeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BureauEtudeRepository extends ntityRepository
{
}
