<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CommercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercialRepository extends EntityRepository
{
}
