<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinitionRepository extends EntityRepository
{

    public function findFinitionIntByBooleanTrue($int)
    {
    	$query = $this->createQueryBuilder('fi')
    		->where('fi.isInterieur = :param')
    		->setParameter('param', $int);
		return $query->getQuery()->getResult();
    }

       public function findFinitionIntByBooleanFalse($ext)
    {
    	$query = $this->createQueryBuilder('fi')
    		->where('fi.isInterieur = :param')
    		->setParameter('param', $ext);
		return $query->getQuery()->getResult();
    }
}
