# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.manager.modele:
        class: AppBundle\Manager\ModeleManager
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: manager.service}
    app_bundle.manager.module:
        class: AppBundle\Manager\ModuleManager
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - {name: manager.service}
    app_bundle.form.devis:
        class: AppBundle\Form\DevisType
        arguments: 
            - "@app_bundle.manager.modele"
            - "@app_bundle.manager.module"
        tags:
            - {name: form.type}