# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.manager.modele:
        class: AppBundle\Manager\ModeleManager
    app_bundle.form.modele:
        class: AppBundle\Form\ModeleType
        arguments: ['@app_bundle.manager.modele']