login:
    path:   /login
    defaults:  { _controller: MaderaBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

madera_devis:
    path:     /madera/devis/{id}
    defaults: { _controller: MaderaBundle:Devis:showDevis }
    requirements:
        id: \d+

madera_devis_projet:
    path:     /madera/link
    defaults: { _controller: MaderaBundle:Project:linkDevis }

madera_index:
    path:     /madera/index
    defaults: { _controller: MaderaBundle:Devis:index }

madera_new_devis:
    path:     /madera/create-devis
    defaults: { _controller: MaderaBundle:Devis:createDevis }

madera_new_project:
    path:     /madera/create-project
    defaults: { _controller: MaderaBundle:Project:createProject }

